tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/core"
tap "homebrew/services"
brew "autoconf"
brew "automake"
brew "bash"
brew "bison"
brew "c-ares"
brew "libpng"
brew "freetype"
brew "fontconfig"
brew "cmake"
brew "openssl"
brew "curl", args: ["with-c-ares", "with-gssapi", "with-libmetalink", "with-libssh2", "with-nghttp2", "with-rtmpdump"]
brew "fftw"
brew "jpeg"
brew "libtiff"
brew "webp"
brew "ghostscript"
brew "git"
brew "go"
brew "gradle"
brew "libtool"
brew "graphviz"
brew "gts"
brew "icu4c"
brew "little-cms2"
brew "openjpeg"
brew "xz"
brew "imagemagick@6", link: true
brew "jenv"
brew "libheif"
brew "liblqr"
brew "libmetalink"
brew "librsvg"
brew "libssh2"
brew "libwmf"
brew "libxml2"
brew "little-cms"
brew "mas"
brew "mcrypt"
brew "mysql", restart_service: true
brew "nghttp2"
brew "pkg-config"
brew "nodenv"
brew "openexr"
brew "perl"
brew "pipenv"
brew "pyenv"
brew "pyenv-virtualenv"
brew "pyenv-virtualenvwrapper"
brew "rbenv"
brew "re2c"
brew "rtmpdump"
brew "screen"
brew "tig"
brew "wget"
brew "yarn"
brew "zip"
brew "zlib"
cask "chatwork"
cask "docker"
cask "dropbox"
cask "github"
cask "google-chrome"
cask "google-cloud-sdk"
cask "google-drive-file-stream"
cask "google-japanese-ime"
cask "iterm2"
cask "karabiner-elements"
cask "macvim"
cask "microsoft-office"
cask "postman"
cask "sequel-pro"
cask "skype"
cask "teamsql"
cask "visual-studio-code"
mas "App Cleaner", id: 1013897218
mas "BetterSnapTool", id: 417375580
mas "Enpass", id: 732710998
mas "Kindle", id: 405399194
mas "LINE", id: 539883307
mas "Slack", id: 803453959
mas "The Unarchiver", id: 425424353
mas "WinArchiver Lite", id: 414855915
mas "Xcode", id: 497799835
